In [1]:
import numpy as np

In [2]:
#part 1
#Instruction: Create 2 1D arrays, y_hat and y
#             Initialize y_hat with 20 linearly spaced numbers between -1 and 1
#             Initialize y with 20 linearly spaced numbers between 0 and 1

#np.linspace is used to create an array with values that are spaced linearly in a specified interval

#y_hat is a 1D array with 20 linearly spaced numbers between -1 and 1
y_hat = np.array([np.linspace(-1, 1, num=20)])

#y is a 1D array with 20 linearly spaced numbers between 0 and 1
y = np.array([np.linspace(0, 1, num=20)])

In [3]:
#output of y_hat
y_hat

array([[-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
        -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
         0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
         0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ]])

In [4]:
#output of y
y

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
        0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
        0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
        0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [5]:
#dimension of y_hat
y_hat.ndim

2

In [6]:
#shape of y_hat
y_hat.shape

(1, 20)

In [7]:
#dimension of y
y.ndim

2

In [8]:
#shape of y
y.shape

(1, 20)

In [9]:
#Create individual functions for each of the loss functions with y and y_hat as parameters

#function for Mean Squared Error
def mean_squared_error(y_hat, y):

   difference = y_hat - y
   differences_squared = difference ** 2
   mean_diff = differences_squared.mean()
   
   return mean_diff

In [10]:
mean_squared_error(y_hat,y)

0.3421052631578948

In [11]:
#function for Mean Absolute Error
def mean_absolute_error(y_hat, y):

   difference = y_hat - y
   abs_difference = np.absolute(difference)
   mean_diff = abs_difference.mean()
   
   return mean_diff

In [12]:
mean_absolute_error(y_hat, y)

0.4999999999999999

In [13]:
#function for Mean Squared Logarithmic Error
def mean_squared_logarithmic_error(y_hat, y):

   first_value = np.log(y_hat+1)
   second_value = np.log(y+1)
   squared_value = (first_value - second_value)**2
   result = squared_value.mean()

   return result

In [14]:
mean_squared_logarithmic_error(y_hat, y)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_14384\3601768426.py:4: RuntimeWarning: divide by zero encountered in log
  first_value = np.log(y_hat+1)


inf

In [15]:
#function for Mean Absolute Percentage Error
def mean_absolute_percentage_error(y_hat, y):

   result = np.mean(np.absolute((y_hat-y)/y_hat))*100

   return result

In [16]:
mean_absolute_percentage_error(y_hat, y)

202.65927536515775

In [17]:
#part 2
#Instruction: Create a 1d array M {1, 2, …16} using the arange function

M = np.arange(1,17)
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [18]:
#Reshape M into 4x4 array and store it to N

N = M.reshape(4,4)
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
#Get the 2nd row of N

N[1]

array([5, 6, 7, 8])

In [20]:
#Get the minimum values for each column of N

min_values = np.min(N, axis=0)
min_values

array([1, 2, 3, 4])

In [21]:
#Get the locations of the minimum values for each column of N

locations = np.argsort(min_values)
locations

array([0, 1, 2, 3], dtype=int64)

In [22]:
#Get the average of the whole matrix

np.average(N)

8.5

In [23]:
#Create a vector V with 4 elements, each element is 1

V = np.array([1,1,1,1])
V

array([1, 1, 1, 1])

In [24]:
#Take the dot product of N and V

np.dot(N,V)

array([10, 26, 42, 58])